apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: tasks
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///radithsandeepa/task-management/dlqcfa/8b1c3/v1.0/ORGANIZATION
      connectionConfig: 01ef02bc-e58b-1666-8705-dc849785e560
      env:
      - from: ServiceURL
        to: TASK_SERVICE_URL
      - from: ConsumerKey
        to: TASKS_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to:  TASKS_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: TASKS_OAUTH_TOKEN_URL